apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: api
      labels:
        app: web
    spec:
      containers:
      - name: api
        image: edsontecno/conversao-temperatura:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: web
  ports:
    - port: 80 
      targetPort: 8080 
      protocol: TCP
      nodePort: 30000
  type: NodePort          